### ISSUE TITLE
Import Error: PyQt5 undefined symbol 

### ISSUE THREAD

**Issue by Lilezh** [bitcraze/crazyflie-clients-python#537] opened 2021-11-03 23:13 UTC
Hi,
I install the clients from the source following the instruction and get the following error when I run the command cfclient. Any idea how to solve this error? I am using Ubuntu 20.04 system. Thank you for your help.

```
lile@jarvis:~$ cfclient

Traceback (most recent call last):
  File "/home/lile/.local/bin/cfclient", line 11, in <module>
    load_entry_point('cfclient', 'console_scripts', 'cfclient')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lile/crazyflie-clients-python/src/cfclient/gui.py", line 39, in <module>
    from quamash import QSelectorEventLoop
  File "/home/lile/.local/lib/python3.8/site-packages/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/lile/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZTI20QTransposeProxyModel, version Qt_5
```

**Comment by knmcguire** [comment] 2021-11-04 17:10
Hi! 

I can not reproduce your error on Ubuntu 20.04. Are you on the latest master of the cfclient source? Do you know which version of the QT gui library you are using right now?

**Comment by Lilezh** [comment] 2021-11-04 17:32
Hi,

I follow the steps in chapter 3.2  of “Flying Multiple UAVs Using ROS”, Springer Book on Robot Operating System (ROS), 2017.  I only make the changes of python3-pyqt4 to python3-pyqt5. Based on those steps, I think I am on the latest master.  I don't know since I am not with the device now but I will let you know when possible. 
```
$sudo apt-get install git python3 python3-pip python3-pyqt5 python3-numpy python3-zmq
$ sudo pip3 install pyusb==1.0.0b2
$ sudo pip3 install pyqtgraph appdirs

$ git clone https://github.com/bitcraze/crazyflie-lib-python.git
$ cd crazyflie-lib-python
$ pip3 install --user -e .

$ cd

$ git clone https://github.com/bitcraze/crazyflie-clients-python.git
$ cd crazyflie-clients-python
$ pip3 install --user -e .

$ cfclient
```

**Comment by knmcguire** [comment] 2021-11-05 16:46
So those instructions are over 4 years old so it's missing packages that you are supposed to install. These are the [most recent instructions to install the cfclient](https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/installation/install/). 

Probably your error can already be fixed with:
`sudo apt install libxcb-xinerama0
`

But if not, do 
`pip3 uninstall cflib cfclient`
and follow the instructions I gave earlier. If you are not planning to do any development on the cfclient itself, just follow the instructions to install for latest release.

Just a note, it's probably not a good idea to use 'sudo' for installing pip packages.

**Comment by Lilezh** [comment] 2021-11-08 21:41
Thanks for your note! I tried to install it directly following the instructions. It still gives me the same error.
```
lile@jarvis:~$ sudo pip3 uninstall cflib cfclient
WARNING: Skipping cflib as it is not installed.
WARNING: Skipping cfclient as it is not installed.

lile@jarvis:~$ sudo apt install git python3-pip libxcb-xinerama0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxcb-xinerama0 is already the newest version (1.14-2).
git is already the newest version (1:2.25.1-1ubuntu3.2).
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
  libgstreamer-plugins-bad1.0-0 libllvm11 libllvm11:i386 libva-wayland2
  libxdamage1:i386 shim
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
lile@jarvis:~$ pip3 install --upgrade pip
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
Successfully installed pip-21.3.1
lile@jarvis:~$ pip3 install cfclient
Defaulting to user installation because normal site-packages is not writeable
Collecting cfclient
  Using cached cfclient-2021.6.1-py3-none-any.whl
Collecting qtm~=2.0.2
  Using cached qtm-2.0.6-py3-none-any.whl (3.1 MB)
Requirement already satisfied: appdirs~=1.4.0 in /usr/local/lib/python3.8/dist-packages (from cfclient) (1.4.4)
Collecting pyzmq~=19.0
  Using cached pyzmq-19.0.2-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Requirement already satisfied: pyqtgraph~=0.11 in /usr/local/lib/python3.8/dist-packages (from cfclient) (0.12.3)
Collecting numpy~=1.19.2
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Requirement already satisfied: PyYAML~=5.3 in /usr/lib/python3/dist-packages (from cfclient) (5.3.1)
Collecting quamash~=0.6.1
  Using cached Quamash-0.6.1-py3-none-any.whl (15 kB)
Collecting pyqt5~=5.15.0
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Collecting pyserial~=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting vispy~=0.6.6
  Using cached vispy-0.6.6-cp38-cp38-manylinux2014_x86_64.whl (2.3 MB)
Collecting cflib>=0.1.16
  Using cached cflib-0.1.16-py2.py3-none-any.whl (168 kB)
Collecting opencv-python-headless==4.5.1.48
  Using cached opencv_python_headless-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl (37.6 MB)
Requirement already satisfied: pyusb>=1.0.0b2 in /usr/local/lib/python3.8/dist-packages (from cflib>=0.1.16->cfclient) (1.0.0b2)
Collecting PyQt5-Qt5>=5.15.2
  Using cached PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
Collecting PyQt5-sip<13,>=12.8
  Using cached PyQt5_sip-12.9.0-cp38-cp38-manylinux1_x86_64.whl (332 kB)
Collecting freetype-py
  Using cached freetype_py-2.2.0-py3-none-manylinux1_x86_64.whl (890 kB)
Installing collected packages: numpy, PyQt5-sip, PyQt5-Qt5, opencv-python-headless, freetype-py, vispy, quamash, qtm, pyzmq, pyserial, pyqt5, cflib, cfclient
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.9.0 cfclient-2021.6.1 cflib-0.1.16 freetype-py-2.2.0 numpy-1.19.5 opencv-python-headless-4.5.1.48 pyqt5-5.15.6 pyserial-3.5 pyzmq-19.0.2 qtm-2.0.6 quamash-0.6.1 vispy-0.6.6

lile@jarvis:~$ cfclient
Traceback (most recent call last):
  File "/home/lile/.local/bin/cfclient", line 5, in <module>
    from cfclient.gui import main
  File "/home/lile/.local/lib/python3.8/site-packages/cfclient/gui.py", line 39, in <module>
    from quamash import QSelectorEventLoop
  File "/home/lile/.local/lib/python3.8/site-packages/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/lile/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZTI20QTransposeProxyModel, version Qt_5
```

**Comment by knmcguire** [comment] 2021-11-09 16:42
Could you send out the result of pip3 list? Maybe there are some conflicting packages that are causing this since you haven't installed cfclient within a python environment

**Comment by Lilezh** [comment] 2021-11-09 18:18
The result is this:

```
lile@jarvis:~$ pip3 list
Package                             Version
----------------------------------- --------------------
actionlib                           1.13.2
angles                              1.9.13
appdirs                             1.4.4
apturl                              0.5.2
atomicwrites                        1.1.5
attrs                               19.3.0
autobahn                            17.10.1
Automat                             0.8.0
bcrypt                              3.1.7
beautifulsoup4                      4.8.2
blinker                             1.4
bondpy                              1.8.6
breezy                              3.0.2
Brlapi                              0.7.0
camera-calibration                  1.15.3
camera-calibration-parsers          1.12.0
catkin                              0.8.10
catkin-pkg                          0.4.24
catkin-pkg-modules                  0.4.24
catkin-tools                        0.7.1
cbor                                1.0.0
certifi                             2019.11.28
cfclient                            2021.6.1
cflib                               0.1.16
chardet                             3.0.4
chrome-gnome-shell                  0.0.0
Click                               7.0
colorama                            0.4.3
command-not-found                   0.3
configobj                           5.0.6
constantly                          15.1.0
controller-manager                  0.19.5
controller-manager-msgs             0.19.5
cryptography                        2.8
cupshelpers                         1.0
cv-bridge                           1.15.0
cycler                              0.10.0
Cython                              0.29.14
dbus-python                         1.2.16
decorator                           4.4.2
defer                               1.0.6
defusedxml                          0.6.0
Deprecated                          1.2.7
diagnostic-analysis                 1.10.4
diagnostic-common-diagnostics       1.10.4
diagnostic-updater                  1.10.4
distro                              1.4.0
distro-info                         0.23ubuntu1
docutils                            0.16
dulwich                             0.19.15
duplicity                           0.8.12.0
dynamic-reconfigure                 1.7.1
empy                                3.3.2
entrypoints                         0.3
et-xmlfile                          1.0.1
fasteners                           0.14.1
fastimport                          0.9.8
freetype-py                         2.2.0
future                              0.18.2
gazebo_plugins                      2.9.2
gazebo_ros                          2.9.2
gencpp                              0.6.5
geneus                              3.0.0
genlisp                             0.4.18
genmsg                              0.5.16
gennodejs                           2.0.2
genpy                               0.6.15
gpg                                 1.13.1-unknown
html5lib                            1.0.1
httplib2                            0.14.0
hyperlink                           19.0.0
idna                                2.8
image-geometry                      1.15.0
importlib-metadata                  1.5.0
incremental                         16.10.1
interactive-markers                 1.12.0
jdcal                               1.0
joint_state_publisher               1.15.0
joint_state_publisher_gui           1.15.0
keyring                             18.0.1
kiwisolver                          1.0.1
language-selector                   0.1
laser_geometry                      1.6.7
launchpadlib                        1.10.13
lazr.restfulclient                  0.14.2
lazr.uri                            1.0.3
lockfile                            0.12.2
louis                               3.12.0
lxml                                4.5.0
lz4                                 3.0.2+dfsg
macaroonbakery                      1.3.1
Mako                                1.1.0
MarkupSafe                          1.1.0
matplotlib                          3.1.2
mavros                              1.9.0
message-filters                     1.15.13
monotonic                           1.5
more-itertools                      4.2.0
mpi4py                              3.0.3
netifaces                           0.10.4
nose                                1.3.7
numexpr                             2.7.1
numpy                               1.19.5
oauthlib                            3.1.0
olefile                             0.46
opencv-python-headless              4.5.1.48
openpyxl                            3.0.3
osrf-pycommon                       1.0.0
packaging                           20.3
pandas                              0.25.3
paramiko                            2.6.0
pexpect                             4.6.0
Pillow                              7.0.0
pip                                 21.3.1
pluggy                              0.13.0
protobuf                            3.6.1
psutil                              5.5.1
py                                  1.8.1
py-ubjson                           0.14.0
pyasn1                              0.4.2
pyasn1-modules                      0.2.1
pycairo                             1.16.2
pycryptodomex                       3.6.1
pycups                              1.9.73
pydot                               1.4.1
PyGithub                            1.43.7
Pygments                            2.3.1
PyGObject                           3.36.0
PyHamcrest                          1.9.0
PyJWT                               1.7.1
pymacaroons                         0.13.0
PyNaCl                              1.3.0
pynmea2                             1.18.0
PyOpenGL                            3.1.0
pyOpenSSL                           19.0.0
pyparsing                           2.4.6
pypng                               0.0.20
PyQRCode                            1.2.1
PyQt5                               5.15.6
PyQt5-Qt5                           5.15.2
PyQt5-sip                           12.9.0
pyqtgraph                           0.12.3
pyRFC3339                           1.1
pyserial                            3.5
pytest                              4.6.9
python-apt                          2.0.0+ubuntu0.20.4.6
python-dateutil                     2.7.3
python-debian                       0.1.36ubuntu1
python-gitlab                       2.0.1
python-gnupg                        0.4.5
python-qt-binding                   0.4.4
python-snappy                       0.5.3
PyTrie                              0.2
pytz                                2019.3
pyusb                               1.0.0b2
pyxdg                               0.26
PyYAML                              5.3.1
pyzmq                               19.0.2
qt-dotgraph                         0.4.2
qt-gui                              0.4.2
qt-gui-cpp                          0.4.2
qt-gui-py-common                    0.4.2
qtm                                 2.0.6
Quamash                             0.6.1
reportlab                           3.5.34
requests                            2.22.0
requests-unixsocket                 0.2.0
resource_retriever                  1.12.6
roman                               2.0.0
rosbag                              1.15.13
rosboost-cfg                        1.15.8
rosclean                            1.15.8
roscreate                           1.15.8
rosdep                              0.21.0
rosdep-modules                      0.21.0
rosdistro                           0.8.3
rosdistro-modules                   0.8.3
rosgraph                            1.15.13
rosinstall                          0.7.8
rosinstall-generator                0.1.22
roslaunch                           1.15.13
roslib                              1.15.8
roslint                             0.12.0
roslz4                              1.15.13
rosmake                             1.15.8
rosmaster                           1.15.13
rosmsg                              1.15.13
rosnode                             1.15.13
rosparam                            1.15.13
rospkg                              1.3.0
rospkg-modules                      1.3.0
rospy                               1.15.13
rosservice                          1.15.13
rostest                             1.15.13
rostopic                            1.15.13
rosunit                             1.15.8
roswtf                              1.15.13
rqt_action                          0.4.9
rqt_bag                             0.5.1
rqt_bag_plugins                     0.5.1
rqt_console                         0.4.11
rqt_dep                             0.4.12
rqt_graph                           0.4.14
rqt_gui                             0.5.2
rqt_gui_py                          0.5.2
rqt_image_view                      0.4.16
rqt_launch                          0.4.9
rqt_logger_level                    0.4.11
rqt-moveit                          0.5.10
rqt_msg                             0.4.10
rqt_nav_view                        0.5.7
rqt_plot                            0.4.13
rqt_pose_view                       0.5.11
rqt_publisher                       0.4.10
rqt_py_common                       0.5.2
rqt_py_console                      0.4.10
rqt-reconfigure                     0.5.4
rqt-robot-dashboard                 0.5.8
rqt-robot-monitor                   0.5.13
rqt_robot_steering                  0.5.12
rqt_runtime_monitor                 0.5.9
rqt-rviz                            0.7.0
rqt_service_caller                  0.4.10
rqt_shell                           0.4.11
rqt_srv                             0.4.9
rqt_tf_tree                         0.6.2
rqt_top                             0.4.10
rqt_topic                           0.4.12
rqt_web                             0.4.10
rviz                                1.14.10
scipy                               1.3.3
screen-resolution-extra             0.0.0
SecretStorage                       2.3.1
sensor-msgs                         1.13.1
service-identity                    18.1.0
setuptools                          45.2.0
simplejson                          3.16.0
sip                                 4.19.21
six                                 1.14.0
smach                               2.5.0
smach-ros                           2.5.0
smbus2                              0.4.1
smclib                              1.8.6
soupsieve                           1.9.5
sparkfun-pi-servo-hat               0.9.0
sparkfun-qwiic                      1.1.2
sparkfun-qwiic-adxl313              0.0.7
sparkfun-qwiic-bme280               0.9.0
sparkfun-qwiic-button               2.0.1
sparkfun-qwiic-ccs811               0.9.4
sparkfun-qwiic-dual-encoder-reader  0.0.2
sparkfun-qwiic-gpio                 0.0.2
sparkfun-qwiic-i2c                  0.9.11
sparkfun-qwiic-icm20948             0.0.1
sparkfun-qwiic-joystick             0.9.0
sparkfun-qwiic-keypad               0.9.0
sparkfun-qwiic-kx13x                1.0.0
sparkfun-qwiic-max3010x             0.0.2
sparkfun-qwiic-micro-oled           0.10.0
sparkfun-qwiic-oled-base            0.0.2
sparkfun-qwiic-oled-display         0.0.2
sparkfun-qwiic-pca9685              0.9.1
sparkfun-qwiic-pir                  0.0.4
sparkfun-qwiic-proximity            0.9.0
sparkfun-qwiic-relay                0.0.2
sparkfun-qwiic-rfid                 2.0.0
sparkfun-qwiic-scmd                 0.9.1
sparkfun-qwiic-serlcd               0.0.1
sparkfun-qwiic-sgp40                0.0.4
sparkfun-qwiic-soil-moisture-sensor 0.0.2
sparkfun-qwiic-tca9548a             0.9.0
sparkfun-qwiic-titan-gps            0.1.1
sparkfun-qwiic-twist                0.9.0
sparkfun-qwiic-vl53l1x              1.0.1
sparkfun-top-phat-button            0.0.2
sparkfun-ublox-gps                  1.1.4
ssh-import-id                       5.10
systemd-python                      234
tables                              3.6.1
tf                                  1.13.2
tf-conversions                      1.13.2
tf2-geometry-msgs                   0.7.5
tf2-kdl                             0.7.5
tf2-py                              0.7.5
tf2-ros                             0.7.5
topic-tools                         1.15.13
Twisted                             18.9.0
txaio                               2.10.0
u-msgpack-python                    2.1
ubuntu-advantage-tools              27.3
ubuntu-drivers-common               0.0.0
ufw                                 0.36
unattended-upgrades                 0.1
urllib3                             1.25.8
usb-creator                         0.3.7
vcstools                            0.1.42
vispy                               0.6.6
wadllib                             1.3.3
wcwidth                             0.1.8
webencodings                        0.5.1
wheel                               0.34.2
wrapt                               1.11.2
wsaccel                             0.6.2
wstool                              0.1.18
xacro                               1.14.10
xkit                                0.0.0
xlrd                                1.1.0
xlwt                                1.3.0
zipp                                1.0.0
zope.interface                      4.7.1

```

**Comment by knmcguire** [comment] 2021-11-09 21:18
ahh that are a lot of packages...

to make sure that none of those are conflicting, perhaps it would be good to run cfclient from an python environment.

you install that with :

`pip3 install virtualenv`

then just make an empty directory, navigate to it and make

`python3 -m venv cfclient-env`

then do 

`source cfclient-env/bin/activate`

you should see (cfclient-env) in front of your name now in the terminal. 

Now install cfclient from the latest release again within that clean environment and run it

```
pip3 install cfclient
cfclient
```
Still seeing the errors? 

btw. You can deactivate it by cding to the directory cfclient-env and enter `deactivate`

**Comment by Lilezh** [comment] 2021-11-09 23:01
Yes, it shows the same error. I am so confused since I use the same step, client works on my laptop but it does not work on this lab desktop.
```
lile@jarvis:~$ pip3 install virtualenv
Defaulting to user installation because normal site-packages is not writeable
Collecting virtualenv
  Downloading virtualenv-20.10.0-py2.py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 7.6 MB/s            
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.3-py2.py3-none-any.whl (496 kB)
     |████████████████████████████████| 496 kB 10.9 MB/s            
Collecting filelock<4,>=3.2
  Downloading filelock-3.3.2-py3-none-any.whl (9.7 kB)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv) (1.14.0)
Collecting backports.entry-points-selectable>=1.0.4
  Downloading backports.entry_points_selectable-1.1.1-py2.py3-none-any.whl (6.2 kB)
Installing collected packages: platformdirs, filelock, distlib, backports.entry-points-selectable, virtualenv
Successfully installed backports.entry-points-selectable-1.1.1 distlib-0.3.3 filelock-3.3.2 platformdirs-2.4.0 virtualenv-20.10.0

lile@jarvis:~$ python3 -m venv cfclient-env

lile@jarvis:~$ source cfclient-env/bin/activate
(cfclient-env) lile@jarvis:~$ pip3 install cfclient
Processing ./.cache/pip/wheels/e7/95/20/0b53935fa3f4eb806806e66e3688948576569cb6e63020a5d1/cfclient-2021.6.1-py3-none-any.whl
Collecting vispy~=0.6.6
  Using cached vispy-0.6.6-cp38-cp38-manylinux2014_x86_64.whl (2.3 MB)
Collecting PyYAML~=5.3
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting quamash~=0.6.1
  Using cached Quamash-0.6.1-py3-none-any.whl (15 kB)
Collecting pyqt5~=5.15.0
  Using cached PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
Collecting pyserial~=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting appdirs~=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting cflib>=0.1.16
  Using cached cflib-0.1.16-py2.py3-none-any.whl (168 kB)
Collecting pyzmq~=19.0
  Using cached pyzmq-19.0.2-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Collecting pyqtgraph~=0.11
  Using cached pyqtgraph-0.12.3-py3-none-any.whl (992 kB)
Collecting numpy~=1.19.2
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Collecting qtm~=2.0.2
  Using cached qtm-2.0.6-py3-none-any.whl (3.1 MB)
Collecting freetype-py
  Using cached freetype_py-2.2.0-py3-none-manylinux1_x86_64.whl (890 kB)
Collecting PyQt5-sip<13,>=12.8
  Using cached PyQt5_sip-12.9.0-cp38-cp38-manylinux1_x86_64.whl (332 kB)
Collecting PyQt5-Qt5>=5.15.2
  Using cached PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
Collecting opencv-python-headless==4.5.1.48
  Using cached opencv_python_headless-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl (37.6 MB)
Collecting pyusb>=1.0.0b2
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Installing collected packages: freetype-py, numpy, vispy, PyYAML, quamash, PyQt5-sip, PyQt5-Qt5, pyqt5, pyserial, appdirs, opencv-python-headless, pyusb, cflib, pyzmq, pyqtgraph, qtm, cfclient
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.9.0 PyYAML-5.4.1 appdirs-1.4.4 cfclient-2021.6.1 cflib-0.1.16 freetype-py-2.2.0 numpy-1.19.5 opencv-python-headless-4.5.1.48 pyqt5-5.15.6 pyqtgraph-0.12.3 pyserial-3.5 pyusb-1.2.1 pyzmq-19.0.2 qtm-2.0.6 quamash-0.6.1 vispy-0.6.6

(cfclient-env) lile@jarvis:~$ cfclient
Traceback (most recent call last):
  File "/home/lile/cfclient-env/bin/cfclient", line 5, in <module>
    from cfclient.gui import main
  File "/home/lile/cfclient-env/lib/python3.8/site-packages/cfclient/gui.py", line 39, in <module>
    from quamash import QSelectorEventLoop
  File "/home/lile/cfclient-env/lib/python3.8/site-packages/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/lile/cfclient-env/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZTI20QTransposeProxyModel, version Qt_5

**Comment by jonasdn** [comment] 2021-11-10 05:59
So the symbol that is undefined should be found in the `libQt5Core.so.5` library, could you check that you have it in your system, my guess would be to look in: `/usr/lib/x86_64-linux-gnu/libQt5Core.so.5`.

This library should be installed with the Ubuntu package: `libqt5core5a` could you check that you have that installed?

**Comment by Lilezh** [comment] 2021-11-10 18:26
Yes, I do have this library.
![1](https://user-images.githubusercontent.com/90261043/141171735-c3388d80-385e-40aa-8e52-68cd17edc5c0.png)

**Comment by knmcguire** [comment] 2021-11-11 17:28
So it's a bit strange... the pyqt5 and libqt5core are the same version as I have on my Ubuntu but it works for me.

One piece that we do not know yet: which version of python3 itself are you using?

You can find that out by

`python3 --version`

**Comment by Lilezh** [comment] 2021-11-11 18:57
I think the python3 version is 3.8.10. Actually I have another question. I have installed cfclient on my laptop successfully (but cannot install it in lab desktop) and set the different addresses to my three crazyflies (I think cfclient cannot control multiple drones using one Crazyradio PA at the same time, right?). Mainly, I will use ros crazyswarm package and mocap system on the lab desktop to control those crazyflies using one Crazyradio PA . As long as the addresses are configured by my laptop's cfclient, I do not need to install the cfclient on the lab desktop? The radio would work normally for crazyswarm package even if the cfclient does not work?

**Comment by knmcguire** [comment] 2021-11-11 19:33
Ah like that! No then you don't need the CFclient as you can also flash the crazyflie firmware from the crazyswarm package. Only the CFclient uses the QT package in this case.

 The only thing that you would need to do on your laptop + cfclient is to change the URI on the crazyflie, so that is something you can easily do with a crazyradio, or usb cable and just connect each crazyflie one by one (make sure that the others are not on), and just change the URIs like that.

So that is something that you can solve for your situation easily, but let's keep this issue open for anybody else that is having this problem.

**Comment by Lilezh** [comment] 2021-11-11 19:39
Thank you so much!

**Closed** 2022-01-10 12:06 UTC
