### ISSUE TITLE
Running from source Windows 10 Error

### ISSUE THREAD

**Issue by mehmetyldz87** [bitcraze/crazyflie-clients-python#383] opened 2019-10-26 18:08 UTC
Hi,

I encountered with this error when I try to run cfclient from source 2019.09 in Windows 10 64bit. 
Python version is 3.7.1 (64bit). Thanks for help. 

![Error](https://user-images.githubusercontent.com/7778498/67624018-99924a80-f834-11e9-813a-d1072451aff2.png)

**Comment by mehmetyldz87** [comment] 2019-10-28 16:05
Is it possible release the .exe file?

**Comment by ataffanel** [comment] 2019-10-29 08:43
I recognize neither of these errors. What command/procedure did you use to install the client?

The exe is automatically built by appveyor, the version 2019.09 is there: https://ci.appveyor.com/project/bitcraze/crazyflie-clients-python/builds/27690804/artifacts. Unfortunately it does not work. I am going to look at the windows situation and try to clean things up to get the build back to a working state.

**Comment by ataffanel** [comment] 2019-10-29 12:02
I reproduced the problem you had and fixed it by upgrading the version of PyQt5. I am closing this issue since it should fix the problem after you run pip install -e . once mode. Feel free to re-open the issue if it is not fixed for you.

**Closed by ataffanel** 2019-10-29 12:02 UTC

**Comment by mehmetyldz87** [comment] 2019-10-30 19:30
Hi @ataffanel 

This error occurs.

![error](https://user-images.githubusercontent.com/7778498/67892011-d75cdf00-fb64-11e9-8d30-d122b10633ad.png)

**Comment by ataffanel** [comment] 2019-10-31 08:29
Good that the build works :-).

For the source install, can you try to ``pip uninstall cfclient``` a couple of time, clone the project in a new directory and install it again. I do not recognize this error but it is an installation script error so resetting things might help.
