### ISSUE TITLE
latest Client does not open on VM

### ISSUE THREAD

**Issue by ViniCast** [bitcraze/crazyflie-clients-python#689] opened 2023-12-01 13:54 UTC
Hello!
I have tested on Linux VM and I did all the setup and CFclient does not open.
I got some errors. What should I do?

![Captura de tela 2023-12-01 105406](https://github.com/bitcraze/crazyflie-clients-python/assets/152622835/19ca6665-199b-4f3a-b944-9425811cb9dd)

**Comment by knmcguire** [comment] 2023-12-05 08:34
That latest does not have something to do with your original issue. Please check out the readme of the bitcraze VM if you installed the extension package: https://github.com/bitcraze/bitcraze-vm. Also make sure to select the crazyradio in the list of usb devices to be connected to your VM.

Any follow-up questions regarding your last question should be asked on https://discussions.bitcraze.io/. The reason why I didn't convert your first question already is that it indicated an actual bug for the cfclient.

**Comment by knmcguire** [comment] 2023-12-05 08:38
There is a similar issue open already as this one. It is for windows but the fault seems to be the same: https://github.com/bitcraze/crazyflie-clients-python/issues/690. So I'll close this one and communicate further as that one proposes the cause for the bug

**Closed by knmcguire** 2023-12-05 08:38 UTC
Labels: bug
