### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#51] opened 2014-02-11 13:17 UTC
Many areas of the UI would benefit from tests. Foremost among them are input handing and config reading/writing. 

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/51
- Originally Reported By: [Allyn Bauer](http://bitbucket.org/allynbauer)
- Originally Created At: 2013-05-18T20:16:10.785

**Comment by ataffanel** [comment] 2017-03-24 10:06
(early) duplicate of #221

**Closed by ataffanel** 2017-03-24 10:06 UTC
Labels: enhancement
