### ISSUE TITLE
cx-freeze and qt5 issues on win10

### ISSUE THREAD

**Issue by babakc** [bitcraze/crazyflie-clients-python#441] opened 2020-09-12 05:12 UTC
PyQt5~=5.15 causes performance issues on win10, as noted here: https://github.com/bitcraze/crazyflie-clients-python/issues/326 
Had to downgrade to 5.12.1 to resolve.

Also, cx_freeze==5.1.1 fails to install on win10. 6.2 installs successfully.

**Comment by ataffanel** [comment] 2020-09-16 08:11
Thanks for the report! My experience is that cx-freeze 6.2 was failing, I have to investigate that further.

I am going to test and possibly revert the pyqt5 version on Windows.

**Comment by ataffanel** [comment] 2020-09-16 09:28
I can confirm that cx-freeze 5.1.1 does not install on Python 3.8, though cx-freeze 6.2 cannot build the Crazyflie firmware, it has been fixed in #435 and we either need to get cx-freeze from git or wait for 6.3 to land. This is the main reason I sticked with python3.6/cx-freeze 5.1 for this release.

I can verify the Qt problem, I will downgrade it and make a new release (since this affects the build as well).

**Closed** 2021-12-07 12:18 UTC
Labels: bug, app:cfclient, platform:windows
