### ISSUE TITLE
Client becomes unresponsive during flight on OSX Sierra

### ISSUE THREAD

**Issue by scottdarch** [bitcraze/crazyflie-clients-python#326] opened 2018-01-22 02:46 UTC
If I use the Crazyflie 2.0 with a flowdeck in hover mode on OSX 10.13.2 the python client becomes unresponsive and has to be force killed. This happens everytime. Strangely the controller continues to work and the drone is responsive so the bug appears to be in the UI only.

**Comment by ataffanel** [comment] 2018-01-24 15:40
Is there anything written in the console when that happen?
How did you install the client?

**Comment by krichardsson** [comment] 2018-01-24 15:43
I'm on OSX 10.12.6 and I can not reproduce the problem. Maybe it is related to High Sierra?

**Comment by scottdarch** [comment] 2018-01-24 17:28
I'm running the client from source (0263fbfcdc93cf26aff968f8f4f0bbf7d3ec1e05). I noticed that the UI can recover if left alone for a long time. It seems like it gets overloaded with data during the flight and doesn't have time to redraw the UI. The overall system appears responsive so it's not ultimately CPU bound. It just seems like something in the python's process is getting bogged down and starving the UI thread.

**Comment by krichardsson** [comment] 2018-01-26 07:22
Yes, it sounds like queues are filling up.

I have upgraded my machine to OSX 10.13.3 but it works fine for me. 

Historically PyQt has caused some problems, which version are you using (you can find out using ```pip list```)?

**Comment by scottdarch** [comment] 2018-01-28 20:38
Was using PyQt 5.9. Upgraded to 5.10. Same issue. UI is unresponsive during flight and for 30-60 seconds after the flight.

**Comment by krichardsson** [comment] 2018-01-29 13:50
I'm also on 5.9. I don't really know what to suggest, sorry!

We have a clean mac here at the office and will try to reproduce your problem.

How did you install python? With brew? Which version are you using?
(I assume you are not using the VM)

**Comment by babakc** [comment] 2019-12-30 08:54
Weirdly, i had the exact same problem with 2019.09.1 on win10. As soon as i'd connect to my CF with flow deck, the UI would become almost unresponsive, and at best would lag/refresh terribly. 

Downgrading to 2019.01 resolved the problem.

**Comment by ataffanel** [comment] 2020-01-13 16:08
I have isolated the problem on Windows as coming from pyqt5 5.13.1 causing performance problem with the attitude indicator on the flight tab.

Reverting to pyqt5 5.12.1 does fix the problem. I am pushing a fix to setup.py reverting to 5.12.1.

**Comment by ataffanel** [comment] 2020-01-14 08:53
Just released a Windows build 19.09.2 which fixes the problem on Windows. Since this issue is fairly old and there has been no new report for OSX, I am closing this issue. Feel free to open a new one in the problem re-occur.

**Closed by ataffanel** 2020-01-14 08:53 UTC
