### ISSUE TITLE
Can't use crazyradio on Mac client

### ISSUE THREAD

**Issue by jerryyip** [bitcraze/crazyflie-clients-python#291] opened 2017-03-23 02:08 UTC
The Python client can't scan my crazyradio pa.
![image](https://cloud.githubusercontent.com/assets/18615354/24228738/0f3859ce-0fb1-11e7-99ee-6d7642643464.png)

And I have got this problem before when I tried to update the firmware of my crazyradio pa. I finally fixed that problem by changing the usb ID in your code as the following picture.
![0102](https://cloud.githubusercontent.com/assets/18615354/24178738/fb1f7cae-0ee5-11e7-8175-2fd6c2e582f3.png)

### **So could it be the same problem? And how could I fix this?**
Thanks.

**Comment by jerryyip** [comment] 2017-03-23 02:36
I found that 
```
INFO:cflib.drivers.cfusb:Looking for devices....
```
but I could not found something like
```
INFO:cflib.drivers.crazyradio:Looking for devices....
```
which is the usb driver for crazyradio.

**Comment by jerryyip** [comment] 2017-03-23 08:30
hi /dev @ataffanel ?

**Comment by ataffanel** [comment] 2017-03-24 08:47
Could you copy-paste the content of help/about/debug? At least the cfclient and interface sections.

**Comment by jerryyip** [comment] 2017-03-24 13:42
```
➜  bin git:(b345d20) cfclient
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.gui:Foundation not found. Menu will show python as application name
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /Users/jy/Documents/crazyflie/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/Users/jy/Library/Application Support/cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.ui.main:This is a MAC - checking if we can apply Progress Bar Stylesheet for Yosemite Skinny Bars
INFO:cfclient.ui.main:Found Yosemite - applying stylesheet
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.drivers.cfusb:Looking for devices....
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Looking for devices
INFO:cfclient.utils.input.inputreaders.pysdl2:Found 0 devices
INFO:cflib.crazyflie:Closing link
INFO:cflib.crazyflie:Callback->Disconnected from []
```

**Comment by ataffanel** [comment] 2017-03-24 13:51
This is not the about box debug tab. The about box should look something like that:
![image](https://cloud.githubusercontent.com/assets/6381499/24296918/4629966e-10a1-11e7-981b-7dcbf6515e80.png)

**Comment by jerryyip** [comment] 2017-03-25 15:54
<img width="511" alt="debug" src="https://cloud.githubusercontent.com/assets/18615354/24323802/55446406-11b6-11e7-8fe8-d744c2d241d1.png">

**Comment by jerryyip** [comment] 2017-03-25 16:00
It said that crazyradio not found. But I did insert it.
<img width="366" alt="usb" src="https://cloud.githubusercontent.com/assets/18615354/24323855/069d85ac-11b7-11e7-8482-35b7973d7169.png">

**Comment by ataffanel** [comment] 2017-03-26 07:40
Thanks for the "system information" screenshot, this would have been the next thing I ask. The problem is that your Crazyradio does not run the crazyradio firmware, it seems to be running the RFStorm firmware. If you are running the crazyradio firmware this is what you will see:
![image](https://cloud.githubusercontent.com/assets/6381499/24329454/bcf2d294-1207-11e7-9fd8-323a0ef6f8f7.png)

You should reprogram (re-flash) the Crazyradio firmware, I suppose using RFStorm tools. 

I close this ticket since this is not a crazyflie-client bug. Feel free to drop by the [forum](https://forum.bitcraze.io/) if you need help reprogramming your Crazyradio.

**Closed by ataffanel** 2017-03-26 07:40 UTC
