### ISSUE TITLE
Can't configure crazyflie 2.0 parameters

### ISSUE THREAD

**Issue by swapnil1704** [bitcraze/crazyflie-clients-python#210] opened 2015-10-02 20:46 UTC
I'm trying to bootload crazyflie 2.0, I could update the firmware but could not change the configuration parameters. The Configure 2.0 option on the client has been grayed out and is not available for 2014.12.3 PC client
I'm using https://github.com/bitcraze/crazyflie-c ... /2014.12.3 PC client.
Can anyone help.

**Comment by ataffanel** [comment] 2015-11-02 15:46
The Configure 2.0 option will be accessible after connecting the Crazyflie. Is it still grayed-out after connecting?

**Comment by ataffanel** [comment] 2015-11-19 09:12
Can't reproduce here. Closing the issue, feel free to re-open it if there is still a bug.

**Closed by ataffanel** 2015-11-19 09:12 UTC
