### ISSUE TITLE
cfclient crashes upon startup 

### ISSUE THREAD

**Issue by mguarro** [bitcraze/crazyflie-clients-python#256] opened 2016-08-10 17:38 UTC
I followed the instructions to build the client for Windows on a Win10 machine and currently get an error saying "cfclient.exe stopped working" this is the output I get from the terminal:

![image](https://cloud.githubusercontent.com/assets/6118404/17563902/5a99246a-5ee6-11e6-9e50-8c3386b3e57a.png)

**Comment by mguarro** [comment] 2016-08-10 19:39
I get the same issue if I run it from source.

**Comment by krichardsson** [comment] 2016-08-12 13:43
The build on Appveyor seems to be OK - https://ci.appveyor.com/project/bitcraze/crazyflie-clients-python
Maybe you can find a lead in the appveyor.yml file that is used to define the Appveyor build?

**Comment by krichardsson** [comment] 2016-08-12 13:49
Ah Sorry! It is not the build it self that is the problem.

**Comment by mguarro** [comment] 2016-08-12 20:33
Yeah it builds fine, it's a runtime issue. It's ok though, I've switched to an OSX machine and have been having success with it there.

**Comment by krichardsson** [comment] 2016-08-13 06:41
Have you tried to use the .exe from the build on Appveyor?
https://ci.appveyor.com/project/bitcraze/crazyflie-clients-python/build/artifacts

**Comment by mguarro** [comment] 2016-08-16 16:26
I have not, I will give it a try in the next few days.

**Comment by krichardsson** [comment] 2016-12-30 14:16
Hi!

Is this still a problem or should I close the issue?

**Comment by theseankelly** [comment] 2017-02-12 16:05
I'm seeing this now as well.

**Comment by ataffanel** [comment] 2017-02-13 12:58
@theseankelly What error are you getting exactly? I just tested and the only problem I could get is with the lib. After updating the lib it worked fine.

We have been modifying the lib lately and you need to have the master from bitcraze/crazyflie-lib-python in order to run the client. We are going to push the lib more often to PyPi to avoid breaking the client.

**Comment by theseankelly** [comment] 2017-02-13 13:55
My errors about missing the leap motion library and missing cwiid match what I saw in mguarro's output above. His didn't call out anything about linuxjsdev not working, but his screenshot would have started after that point anyway.

```
(cfclient) C:\Users\seankel>cfclient
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from c:\users\seankel\projects\crazyflie\official_repos\crazyflie-clients-python\src\cfclient/configs/config.json
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
===== 2017.02.13 05:02:48 =====
Traceback (most recent call last):
  File "C:\Users\seankel\AppData\Local\Continuum\Miniconda3\envs\cfclient\Scripts\cfclient-script.py", line 11, in <module>
    load_entry_point('cfclient', 'console_scripts', 'cfclient')()
  File "c:\users\seankel\projects\crazyflie\official_repos\crazyflie-clients-python\src\cfclient\gui.py", line 135, in main
    from .ui.main import MainUI
  File "c:\users\seankel\projects\crazyflie\official_repos\crazyflie-clients-python\src\cfclient\ui\main.py", line 33, in <module>
    import cfclient.ui.tabs
  File "c:\users\seankel\projects\crazyflie\official_repos\crazyflie-clients-python\src\cfclient\ui\tabs\__init__.py", line 41, in <module>
    from .locopositioning_tab import LocoPositioningTab
  File "c:\users\seankel\projects\crazyflie\official_repos\crazyflie-clients-python\src\cfclient\ui\tabs\locopositioning_tab.py", line 44, in <module>
    from lpslib.lopoanchor import LoPoAnchor
ImportError: No module named 'lpslib'
```

**Comment by ataffanel** [comment] 2017-02-14 13:41
The wiimote and leap lib are not the cause of the crash, those are import that can fail, they will just disable the linked functionality.

Your problem comes from an outdated cflib: it can be fixed by pulling the latest version of crazyflie-lib-python and installing it with pip install -e .
The module that fails has been added there: https://github.com/bitcraze/crazyflie-lib-python/commit/39b54d7b456660eae0751dc21f74ef95670ebbf1

Did you run your client with the lib from pip? We need to find a way to add functionality to the lib without breaking the client for everyone ...

**Comment by theseankelly** [comment] 2017-02-15 14:46
hmm, yeah that worked. In the past, the README from crazyflie-clients-python worked fine (python pip install -e .[dev] from the crazyflie-clients-python directory, provided crazyflie-lib-python was present in the same parent directory. Looks like I have to run it from the python lib directory as well now. Problem solved for me.

**Comment by krichardsson** [comment] 2017-02-16 08:45
OK, seems like all is good :-) 
Closing

**Closed by krichardsson** 2017-02-16 08:45 UTC
